### ISSUE TITLE
Duplicate code snippets

### ISSUE THREAD

**Issue by derekrushforth** [wildbit/beanstalk-code-snippet-bot#8]
**Conditions for this to happen**
- @beanstalk-snippet-bot is invited to the channel
- In the same channel use slash command `/code [bs_url]`

The bot hears that the message was posted to the channel and looks up the snippet. The slash command request is also sent to our server and looks up the snippet. Thus resulting in duplicate messages.

<img width="530" alt="screen shot 2016-05-17 at 7 11 06 am" src="https://cloud.githubusercontent.com/assets/3054417/15325252/ab329756-1bfe-11e6-9823-0d648ed4194e.png">

**Comment by derekrushforth** [comment]
@okonet one solution is to remove the listener for `ambient` messages. This would fix it.

https://github.com/wildbit/beanstalk-code-snippet-bot/blob/master/src/bot.js#L43

**Comment by okonet** [comment]
PR?

**Comment by okonet** [comment]
Actually I disagree. AFAIK `ambient` is the only reason it works now... Or am I missing something?

**Comment by derekrushforth** [comment]
Yeah, it would end up disabling the ability to listen to any message on in a channel that it's invited to. 

Instead, on this listener maybe we could disable the lookup if we notice that `/code` is in the message.

**Comment by okonet** [comment]
Yeah, the latter should work I think.

**Comment by derekrushforth** [comment]
Cool. I'll do this later tonight.

**Comment by derekrushforth** [comment]
Fixed in abe16979542f0b70418879d580f6c8c617dbd29b
